import { AppState } from './types';
import { BRAND_RED } from './constants';

// Egyszerű OG sablonok
export interface OGTemplate {
  key: string;
  name: string;
  description: string;
  state: Partial<AppState>;
}

export const OG_TEMPLATES: OGTemplate[] = [
  {
    key: 'reset',
    name: 'Alapértelmezett (üres)',
    description: 'Visszaállítja az OG szerkesztőt az alapértelmezett, üres állapotra.',
    state: {}, // üres, az App.tsx úgyis az INITIAL_STATE-tel dolgozik
  },
  {
    key: 'blog',
    name: 'Blog cikk',
    description: 'Címes, szerzős, letisztult blog OG-kép',
    state: {
      backgroundType: 'gradient',
      gradient: { type: 'linear', color1: BRAND_RED, color2: '#fff', angle: 120 },
      layers: [
        {
          id: 'title',
          type: 'text',
          name: 'Cím',
          content: 'Blogcikk címe',
          fontSize: 48,
          fontWeight: '700',
          fontFamily: 'Inter',
          textColor: '#1f2937',
          x: 80,
          y: 180,
          width: 800,
          textAlign: 'left',
          verticalAlign: 'top',
          isVisible: true,
          opacity: 1,
          zIndex: 1,
          letterSpacing: 0,
          lineHeightMultiplier: 1.1,
          textShadow: { enabled: false, color: '#000', offsetX: 0, offsetY: 0, blurRadius: 0 },
          rotation: 0,
        },
        {
          id: 'author',
          type: 'text',
          name: 'Szerző',
          content: 'Szerző neve',
          fontSize: 24,
          fontWeight: '400',
          fontFamily: 'Inter',
          textColor: '#555',
          x: 80,
          y: 260,
          width: 600,
          textAlign: 'left',
          verticalAlign: 'top',
          isVisible: true,
          opacity: 1,
          zIndex: 2,
          letterSpacing: 0,
          lineHeightMultiplier: 1.1,
          textShadow: { enabled: false, color: '#000', offsetX: 0, offsetY: 0, blurRadius: 0 },
          rotation: 0,
        },
      ],
    },
  },
  {
    key: 'quote',
    name: 'Idézet',
    description: 'Kiemelt idézet, középre rendezve, nagy betűkkel.',
    state: {
      backgroundType: 'solid',
      bgColor: '#fffbe6',
      layers: [
        {
          id: 'quote',
          type: 'text',
          name: 'Idézet',
          content: '„Az OG-képek fontosak!”',
          fontSize: 40,
          fontWeight: '600',
          fontFamily: 'Georgia',
          textColor: BRAND_RED,
          x: 600,
          y: 300,
          width: 800,
          textAlign: 'left',
          verticalAlign: 'middle',
          isVisible: true,
          opacity: 1,
          zIndex: 1,
          letterSpacing: 0,
          lineHeightMultiplier: 1.2,
          textShadow: { enabled: false, color: '#000', offsetX: 0, offsetY: 0, blurRadius: 0 },
          rotation: 0,
        },
      ],
    },
  },
  {
    key: 'product',
    name: 'Termék',
    description: 'Termékfotó, ár, cím, modern overlay-el.',
    state: {
      backgroundType: 'image',
      bgImage: '', // A felhasználó tölti fel
      bgImageFilters: { blur: 0, brightness: 100, contrast: 100 },
      overlay: { color: '#00000099', opacity: 0.3 },
      layers: [
        {
          id: 'product-title',
          type: 'text',
          name: 'Termék neve',
          content: 'Termék neve',
          fontSize: 44,
          fontWeight: '700',
          fontFamily: 'Inter',
          textColor: '#fff',
          x: 600,
          y: 120,
          width: 700,
          textAlign: 'left',
          verticalAlign: 'top',
          isVisible: true,
          opacity: 1,
          zIndex: 1,
          letterSpacing: 0,
          lineHeightMultiplier: 1.1,
          textShadow: { enabled: true, color: '#0008', offsetX: 2, offsetY: 2, blurRadius: 8 },
          rotation: 0,
        },
        {
          id: 'price',
          type: 'text',
          name: 'Ár',
          content: 'Ár: 9990 Ft',
          fontSize: 32,
          fontWeight: '600',
          fontFamily: 'Inter',
          textColor: BRAND_RED,
          x: 600,
          y: 200,
          width: 400,
          textAlign: 'left',
          verticalAlign: 'top',
          isVisible: true,
          opacity: 1,
          zIndex: 2,
          letterSpacing: 0,
          lineHeightMultiplier: 1.1,
          textShadow: { enabled: true, color: '#fff', offsetX: 1, offsetY: 1, blurRadius: 4 },
          rotation: 0,
        },
      ],
    },
  },
  {
    key: 'event',
    name: 'Esemény',
    description: 'Esemény OG: dátum, helyszín, cím, színes háttérrel.',
    state: {
      backgroundType: 'gradient',
      gradient: { type: 'radial', color1: '#FF3B30', color2: '#FFD600', angle: 0 },
      layers: [
        {
          id: 'event-title',
          type: 'text',
          name: 'Esemény címe',
          content: 'Graphly Meetup 2025',
          fontSize: 42,
          fontWeight: '800',
          fontFamily: 'Inter',
          textColor: '#fff',
          x: 600,
          y: 180,
          width: 800,
          textAlign: 'left',
          verticalAlign: 'top',
          isVisible: true,
          opacity: 1,
          zIndex: 1,
          letterSpacing: 1,
          lineHeightMultiplier: 1.1,
          textShadow: { enabled: true, color: '#0006', offsetX: 2, offsetY: 2, blurRadius: 8 },
          rotation: 0,
        },
        {
          id: 'event-date',
          type: 'text',
          name: 'Dátum',
          content: '2025. június 30.',
          fontSize: 28,
          fontWeight: '700',
          fontFamily: 'Inter',
          textColor: '#FFD600',
          x: 600,
          y: 260,
          width: 600,
          textAlign: 'left',
          verticalAlign: 'top',
          isVisible: true,
          opacity: 1,
          zIndex: 2,
          letterSpacing: 0,
          lineHeightMultiplier: 1.1,
          textShadow: { enabled: true, color: '#000', offsetX: 1, offsetY: 1, blurRadius: 4 },
          rotation: 0,
        },
        {
          id: 'event-location',
          type: 'text',
          name: 'Helyszín',
          content: 'Budapest, Graphly HQ',
          fontSize: 24,
          fontWeight: '600',
          fontFamily: 'Inter',
          textColor: '#fff',
          x: 600,
          y: 310,
          width: 600,
          textAlign: 'left',
          verticalAlign: 'top',
          isVisible: true,
          opacity: 1,
          zIndex: 3,
          letterSpacing: 0,
          lineHeightMultiplier: 1.1,
          textShadow: { enabled: true, color: '#000', offsetX: 1, offsetY: 1, blurRadius: 4 },
          rotation: 0,
        },
      ],
    },
  },
  {
    key: 'funny',
    name: 'Mém/poén',
    description: 'Vicces OG sablon: nagy, színes, középre igazított szöveg.',
    state: {
      backgroundType: 'solid',
      bgColor: '#00FFB2',
      layers: [
        {
          id: 'meme',
          type: 'text',
          name: 'Poén',
          content: '„Ez egy OG mém!”',
          fontSize: 60,
          fontWeight: '900',
          fontFamily: 'Comic Sans MS',
          textColor: '#FF3B30',
          x: 600,
          y: 300,
          width: 900,
          textAlign: 'left',
          verticalAlign: 'middle',
          isVisible: true,
          opacity: 1,
          zIndex: 1,
          letterSpacing: 2,
          lineHeightMultiplier: 1.1,
          textShadow: { enabled: true, color: '#fff', offsetX: 3, offsetY: 3, blurRadius: 8 },
          rotation: -5,
        },
      ],
    },
  },
  {
    key: 'minimal-dark',
    name: 'Minimalista sötét',
    description: 'Letisztult, sötét háttér, fehér szöveggel, modern betűtípussal.',
    state: {
      backgroundType: 'solid',
      bgColor: '#18181B',
      layers: [
        {
          id: 'title',
          type: 'text',
          name: 'Cím',
          content: 'Minimalista OG-kép',
          fontSize: 56,
          fontWeight: '700',
          fontFamily: 'Montserrat',
          textColor: '#fff',
          x: 120,
          y: 220,
          width: 960,
          textAlign: 'left',
          verticalAlign: 'middle',
          isVisible: true,
          opacity: 1,
          zIndex: 1,
          letterSpacing: 0,
          lineHeightMultiplier: 1.15,
          textShadow: { enabled: false, color: '#000', offsetX: 0, offsetY: 0, blurRadius: 0 },
          rotation: 0,
        },
      ],
    },
  },
  {
    key: 'gradient-modern',
    name: 'Modern gradient',
    description: 'Színes, átmenetes háttér, középre rendezett, nagy szöveggel.',
    state: {
      backgroundType: 'gradient',
      gradient: { type: 'linear', color1: '#7F00FF', color2: '#E100FF', angle: 135 },
      layers: [
        {
          id: 'main',
          type: 'text',
          name: 'Fő szöveg',
          content: 'Modern OG sablon',
          fontSize: 64,
          fontWeight: '900',
          fontFamily: 'Poppins',
          textColor: '#fff',
          x: 100,
          y: 250,
          width: 1000,
          textAlign: 'left',
          verticalAlign: 'middle',
          isVisible: true,
          opacity: 1,
          zIndex: 1,
          letterSpacing: 1,
          lineHeightMultiplier: 1.05,
          textShadow: { enabled: true, color: '#0006', offsetX: 2, offsetY: 2, blurRadius: 10 },
          rotation: 0,
        },
      ],
    },
  },
  {
    key: 'photo-overlay',
    name: 'Fotó overlay',
    description: 'Háttérkép, sötét overlay, világos szöveg, letisztult stílus.',
    state: {
      backgroundType: 'image',
      bgImage: '', // A felhasználó tölti fel
      bgImageFilters: { blur: 0, brightness: 100, contrast: 100 },
      overlay: { color: '#18181B', opacity: 0.55 },
      layers: [
        {
          id: 'headline',
          type: 'text',
          name: 'Főcím',
          content: 'Fotó + overlay',
          fontSize: 52,
          fontWeight: '700',
          fontFamily: 'Raleway',
          textColor: '#fff',
          x: 120,
          y: 260,
          width: 960,
          textAlign: 'left',
          verticalAlign: 'middle',
          isVisible: true,
          opacity: 1,
          zIndex: 1,
          letterSpacing: 0,
          lineHeightMultiplier: 1.1,
          textShadow: { enabled: true, color: '#0008', offsetX: 2, offsetY: 2, blurRadius: 8 },
          rotation: 0,
        },
      ],
    },
  },
  {
    key: 'elegant-light',
    name: 'Elegáns világos',
    description: 'Világos, elegáns háttér, sötét szöveggel, modern betűtípussal.',
    state: {
      backgroundType: 'solid',
      bgColor: '#F8F8F8',
      layers: [
        {
          id: 'main',
          type: 'text',
          name: 'Cím',
          content: 'Elegáns OG template',
          fontSize: 48,
          fontWeight: '700',
          fontFamily: 'Nunito',
          textColor: '#22223B',
          x: 120,
          y: 240,
          width: 960,
          textAlign: 'left',
          verticalAlign: 'middle',
          isVisible: true,
          opacity: 1,
          zIndex: 1,
          letterSpacing: 0,
          lineHeightMultiplier: 1.18,
          textShadow: { enabled: false, color: '#000', offsetX: 0, offsetY: 0, blurRadius: 0 },
          rotation: 0,
        },
        {
          id: 'subtitle',
          type: 'text',
          name: 'Alcím',
          content: 'Letisztult, világos OG-kép',
          fontSize: 28,
          fontWeight: '400',
          fontFamily: 'Nunito',
          textColor: '#4A4E69',
          x: 120,
          y: 320,
          width: 960,
          textAlign: 'left',
          verticalAlign: 'middle',
          isVisible: true,
          opacity: 1,
          zIndex: 2,
          letterSpacing: 0,
          lineHeightMultiplier: 1.1,
          textShadow: { enabled: false, color: '#000', offsetX: 0, offsetY: 0, blurRadius: 0 },
          rotation: 0,
        },
      ],
    },
  },
];
